### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by anjuved** [IntroToCode/RecipesCodemates10#7]
## 💬 Discussion topic

instructions from the assignment - I noticed we hadn't followed some of them (bolded)

## ❗ Potential issues

Your Codemates team used Issues to clearly delineate work (30%)
Was there stated acceptance criteria?
Is there a clear discussion happening amongst the group?
Have all the issues been closed when resolved?
Your Codemates team used Pull Requests to supply multiple solutions (40%)
**Did every team member commit to the Pull Requests?** --> please don't merge until everyone has committed
Did the team use the reviews feature of GitHub to get explicit approval? 
Did at least TWO people approve each Pull Request? 
Work collaboratively on changes until objective is completed (30%)
Are there (3) fully completed recipes on the main/master branch?
Was there healthy disagreement? Discussion of style in the Pull Requests? 

## 👥 People to consult

everyone - @IntroToCode/codemates10

**Comment by jravellana** [comment]
Hi all, checking in on status of the outline @anjuved provided, I believe this is where we're at, but let me know if you all see otherwise! 

1. Your Codemates team used Issues to clearly delineate work (30%): 

- [x] Was there stated acceptance criteria?: 
Good recipes, emojis in title, clear and easy to understand 

- [x] Is there a clear discussion happening amongst the group?: 
Yup

- [ ] **Have all the issues been closed when resolved?:** 
Will be completed once all recipes will be pulled onto the main branch

2. Your Codemates team used Pull Requests to supply multiple solutions (40%)

- [ ] **Did every team member commit to the Pull Requests?**: 
I think @anjuved, @maryyyao, and I have sent commits to Pull Requests, @luke-hedlund & @cake0521 I think you both might need to "commit to pull-requests" <-no idea if I'm using that right

- [ ] **Did the team use the reviews feature of GitHub to get explicit approval?:** 
I think this is when you submit pull requests and request reviews from people, and not just merging directly  

- [ ] **Did at least TWO people approve each Pull Request?**: 
Need to confirm if this has happened on every pull request, not sure, might need to submit new pull requests to satisfy 

3. Work collaboratively on changes until objective is completed (30%)

- [ ] **Are there (3) fully completed recipes on the main/master branch?**: 
Should be the final output

- [x] Was there healthy disagreement? Discussion of style in the Pull Requests?:
Yup
